packaging_format = 2

id = "iceshrimp"
name = "Iceshrimp"
description.en = "Decentralized and federated social networking service"
description.fr = "Service de réseau social décentralisé et fédéré"

version = "2023.12.7~ynh1"

maintainers = ["oufmilo"]

[upstream]
license = "AGPL-3.0"
website = "https://iceshrimp.dev"
code = "https://iceshrimp.dev/iceshrimp/iceshrimp"

[integration]
yunohost = ">= 11.2.12"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "2G"
ram.runtime = "2G"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Iceshrimp will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Iceshrimp sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3020

    [resources.apt]
    packages = "ffmpeg, postgresql, build-essential, git, git-lfs"

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
