test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

      exclude = ["change_url"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.6bd676e.name = "2023.12.1"
    test_upgrade_from.c8ff29b.name = "2023.12.2"